language: ruby

branches:
  except:
    - gh-pages

rvm:
  - 2.1.0
  - 2.0.0

before_install:
  - wget http://ipecho.net/plain -O - -q ; echo # print out external ip

  - gem update --system
  - gem update

  - gem install sass compass jekyll rdiscount cucumber selenium-webdriver

  - gem --version
  - sass --version
  - compass --version
  - firefox --version
  - phantomjs --version

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - compass compile ./assets/css/
  - rake jekyll detach=true
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - rake unittests
  - rake cucumber