language: ruby

branches:
  except:
    - gh-pages

rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0

before_install:
  - wget http://ipecho.net/plain -O - -q ; echo # print out external ip

  - sudo apt-get install chromium-browser unzip
  - sudo wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - mkdir -p ./chromedriver
  - mv chromedriver ./chromedriver
  - echo "export PATH=$PATH:./chromedriver" >> $HOME/.bash_profile
  - which chromedriver

  - gem update --system
  - gem update

  - gem install sass compass jekyll kramdown cucumber selenium-webdriver

  - gem --version
  - sass --version
  - compass --version
  - firefox --version
  - phantomjs --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - compass compile ./assets/css/
  - rake jekyll detach=true
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - rake unittests
  - rake cucumber