language: ruby

branches:
  except:
    - gh-pages

rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0

before_install:
  - pwd
  - wget http://ipecho.net/plain -O - -q ; echo # print out external ip

  - sudo apt-get install chromium-browser unzip

  - wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - chmod +x ~/Downloads/chromedriver
  - sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - which chromedriver

  - gem update --system
  - gem update

  - gem install sass compass jekyll kramdown cucumber selenium-webdriver

  - gem --version
  - sass --version
  - compass --version
  - firefox --version
  - phantomjs --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - rake jekyll watch_compass=false
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - rake unittests
  - rake cucumber